name: CI

on:
  push:
    branches:
    - master
    - release-*
    tags:
    - '*.*.*'
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push
      env:
        MYGET_JBOGARD_CI_API_KEY: ${{ secrets.MYGET_JBOGARD_CI_API_KEY }}
      run: ./Push.ps1
      shell: pwsh