name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
